### ISSUE TITLE
Beispiele UUIDs

### ISSUE THREAD

**Issue by lmaylein** [ssciwr/svelte-easydb-detail-view#47]
Nicole hat mir noch weitere Beispiele geschickt, die Du, wenn Du möchtest, in die vorkonfigurierten Beispiel UUIDs aufnehmen könntest:

    Sehr ausführlich, normierte Listen = a3f6109f-feb4-45f8-8e76-c4466efd0d20
    Sehr ausführlich, Beziehungen = bb7c84ae-4796-4c20-8df0-a4c5c49a7ac6
    Sehr ausführlich, viele Beziehungen = 1fde05f5-7767-448f-a104-4f4af9d8f9ed
    Hierarchie (Über- und untergeordneten Datensätze) = e95dcb74-77f6-4794-b468-506da8b7a3a1
    Sehr viele Aufnahmen + Hierarchie = a1b154b0-2c89-4317-8bac-2a7e684740b8

**Comment by dokempf** [comment]
Ihr wisst aber dass ihr jede beliebige UUID in das Frld UUID reinkopieren könnt, oder? Die Buttons waren nur für mich um beim Testen schnell hin und her zu wechseln.

**Comment by dokempf** [comment]
Sind nun implementiert.
